# Perform a Gradle `build` which includes `assemble`, `check`, `test`
# of the projects, and uploads the generated artifacts.

name: Generate releaseble artifacts

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Runs this job in parallel for each sub-project
    strategy:
      matrix:
        project-dir:
          - strict-version-matcher-plugin
          - oss-licenses-plugin
          - google-services-plugin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: Perform a Gradle build
        working-directory: ./${{ matrix.project-dir }}
        run: ./gradlew publish
      - name: Upload generated artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ matrix.project-dir }}
          path: ./${{ matrix.project-dir }}/build/repo
          retention-days: 5
