# Perform a Gradle `build` which includes `assemble`, `check`, `test`
# of the projects, and uploads the generated artifacts.

name: Generate releaseble artifacts

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Runs this job in parallel for each sub-project
    strategy:
      matrix:
        project-dir:
          - strict-version-matcher-plugin
          - oss-licenses-plugin
          - google-services-plugin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
      - name: Perform a Gradle build
        working-directory: ./${{ matrix.project-dir }}
        run: ./gradlew publish
      - name: Upload generated artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ matrix.project-dir }}
          path: ./${{ matrix.project-dir }}/build/repo
          retention-days: 5
