name: Lint

on:
  workflow_call: # This makes it "callable" by other workflows

permissions:
  contents: read

jobs:
  lint-and-check:
    name: Run linters and checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/wrapper-validation@v6.3.0
      - name: Lint GitHub Actions
        uses: abcxyz/actions/.github/actions/lint-github-actions@3894a8d6a18b9aa159fe9092501d523d97f07110 # ratchet:abcxyz/actions/.github/actions/lint-github-actions@main
      - name: Ratchet Check
        uses: sethvargo/ratchet@a7ead07a89972fef4316ad196af18f87ac77bb97 # ratchet:sethvargo/ratchet@main
        with:
          files: .github/workflows/*.yml
